# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 18.17
          registry-url: https://npm.pkg.github.com/
      - uses: actions/checkout@v4
      - name: check if the package already exist
        id: publish
        run: |
          set -x
          VERSION=$(awk '/version/{print $NF}'  package.json  | tr -d '",')
          PUBLISH=$(npm info  @impargo/${PACKAGE}@${VERSION} --json | sed -n 's/homepage/&/p' | wc -l)
          if [ $PUBLISH -eq 0 ]
          then
            echo "::set-output name=alreadyPublished::false"
          else
            echo "skipping publish, package @impargo/${PACKAGE}@${VERSION} already published"
            echo "::set-output name=alreadyPublished::true"
          fi
        env:
          PACKAGE: "@impargo/lexoffice-client-js"
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: cache
        if: steps.publish.outputs.alreadyPublished == 'false'
        uses: actions/cache@v4
        with:
          path: node_modules 
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
      - name: Install
        if: steps.publish.outputs.alreadyPublished == 'false'
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Lint
      #   if: steps.publish.outputs.alreadyPublished == 'false'
      #   run: yarn run lint
      # - name: Test
      #   if: steps.publish.outputs.alreadyPublished == 'false'
      #   run: yarn test
      - name: Build
        if: steps.publish.outputs.alreadyPublished == 'false'
        run: yarn build
      - name: Publish
        if: steps.publish.outputs.alreadyPublished == 'false'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

