name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Pull latest changes
        run: git pull origin main
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.17
      - name: cache
        uses: actions/cache@v2
        with:
          path: node_modules 
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
      - name: npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install
        run: |
          yarn install --frozen-lockfile
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_ACCESS_TOKEN }}
        run: npx semantic-release
